apiVersion: v1
kind: ResourceQuota
metadata:
  name: xbid-mainnet-budget
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 10Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "5"
    requests.storage: 150Gi
