apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database-schema.yaml
  - frontend.yaml
  - backend.yaml
  - indexer.yaml
  - uploads.yaml
  - network-policies.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: xbid
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
