apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xbid-testnet
resources:
  - ../../base
  - namespace.yaml
  - database.yaml
  - ingress.yaml
  - quota.yaml
configMapGenerator:
  - name: xbid-environment
    envs:
      - environment.env
generatorOptions:
  disableNameSuffixHash: false
images:
  - name: ghcr.io/xbidlive/xbid-frontend
    newTag: testnet
  - name: ghcr.io/xbidlive/xbid-backend
    newTag: main
  - name: ghcr.io/xbidlive/xbid-indexer
    newTag: main
